# Data that are not included in the repository:
# 1. TAIR10.fasta
# 2. TIGER script for distribution
# 3. bowtie2 reference genoome
# Above files should be prepared by the user.

THREADS: 30
MEMORY: "300g"
LIBRARY_INFO:
  sample_size: 96
  # datein lib_name: (if possible) annotate library name with the date when macrogen finished sequencing
  lib_name: "20231122_hta7-set1"
FILTER:
  cutadapt:
      cut_R1_5prime: 9 # -u (Cut 8bp index + T-OH from 5'end of Read1)
      trim_R1_3prime: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGA" # -a
      trim_R2_3prime_file: "data/GBS_adapter_P1_R.txt" # -A
      quality-filter: 19 # -q
      minimum-overlap: 3 # -O (default: 3)
# NOTE: reference genome-specific mapping parameters
MAPPING:
      # alignments: 10 # "In -k <N> mode, Bowtie 2 searches for up to N distinct, valid alignments for each read" However, the MAPQ becomes meaningless in -k mode. Thus I disable this option in bowtie2 rule.
      reference: "/home/nison/work/refgenome/TAIR10/bowtie2_index/tair10"
      # True multiread can get MAPQ 0 or 1. In the GBS analysis I only take primary reads but the primary reads of the true multiread is random: So I filter out the alignments with MAPQ below 2.
      MAPQmaxi: 2 # -q
      sortMemory: "5G"
MARKER:
  complete_gz: "data/ColLer_markers/BC.complete.tsv.gz"
  complete: "data/ColLer_markers/BC.complete.tsv"
  mask: "data/ColLer_markers/BC.mask.tsv"
REFGENOME: 
  fasta: "/home/nison/work/refgenome/TAIR10/TAIR10.fasta"
  fai: "/home/nison/work/refgenome/TAIR10/TAIR10.fasta.fai"
TSV:
  binSize: 100000
  binName: "100kb"
SCRIPTS:
  tigercall2tigerin: "src/tigercalls2tiger.R"
  tiger: "/usr/local/src/GBS_suite/TIGER_Scripts-for-distribution"
  runtiger: "src/runTiger.sh"
  cotable: "src/GBS_cotable.R"
  toTSV: "src/cotableToGenomeBinTSV.R"
  plot: "src/CO_landscape.R"
PLOT:
  ma_width: 7

# NEBNext adapter and universal primer for Illumina:
# https://international.neb.com/-/media/catalog/datacards-or-manuals/manuale7335.pdf
# https://www.biostars.org/p/149301/
# https://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq
# http://bioinformatics.cvr.ac.uk/blog/illumina-adapter-and-primer-sequences/
# TruSeq adapters:
# http://emea.support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
