THREADS: 30
MEMORY: "300g"
FILTER:
  fastqc:
      adapters: "/datasets/data_4/nison/GBS/for_snakemake/data/fastqc_adapters.txt"
  cutadapt:
      cut_R1_5prime: 9 # -u (Cut 8bp index + T-OH from 5'end of Read1)
      adapter_R1_3prime: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGA" # -a
      adapter_R2_3prime_file: "/datasets/data_4/nison/GBS/for_snakemake/data/GBS_adapter_P1_R.txt" # -A
      quality-filter: 19 # -q
      minimum-overlap: 3 # -O (default: 3)
# NOTE: reference genome-specific mapping parameters
MAPPING:
      # alignments: 10 # "In -k <N> mode, Bowtie 2 searches for up to N distinct, valid alignments for each read"
      reference: "/datasets/data_4/nison/GBS/for_snakemake/data/bowtie2_index/tair10"
      MAPQmaxi: 10 # -q
      sortMemory: "5G"
MARKER:
  complete_gz: "/datasets/data_4/nison/GBS/for_snakemake/data/ColLer_markers/BC.complete.tsv.gz"
  complete: "/datasets/data_4/nison/GBS/for_snakemake/data/ColLer_markers/filter_arp6-deletion/BC.complete.arp6_filter.tsv"
  mask: "/datasets/data_4/nison/GBS/for_snakemake/data/ColLer_markers/filter_arp6-deletion/BC.mask.arp6_filter.tsv"
REFGENOME: "/home/nison/work/refgenome/TAIR10/TAIR10.fasta"
SCRIPTS:
  tigercall2tigerin: "/datasets/data_4/nison/GBS/for_snakemake/src/tigercalls2tiger.R"
  tiger: "/datasets/data_4/nison/GBS/for_snakemake/src/runTiger.sh"
  cotable: "/datasets/data_4/nison/GBS/for_snakemake/src/GBS_cotable.R"
COTABLE:
  # number of library to summarize
  num_lib: 96
  lib_name: "arp6-2023"

# NEBNext adapter and universal primer for Illumina:
# https://international.neb.com/-/media/catalog/datacards-or-manuals/manuale7335.pdf
# https://www.biostars.org/p/149301/
# https://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq
# http://bioinformatics.cvr.ac.uk/blog/illumina-adapter-and-primer-sequences/
# TruSeq adapters:
# http://emea.support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
